name: Build and deploy to GitHub Pages

on:
  push:
    branches: [ pelican ]
  pull_request:
    branches: [ pelican ]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: errata-ai/vale-action@v2.1.1
        with:
          files: content/
      - uses: actions/setup-python@v6
        with:
          cache: 'pip'
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: generate output
        run: pelican -v
      - name: publish
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: master
